name: Monorepo CI/CD

on:
  push:
    branches:
      - release

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Build Packages
        run: yarn build

      - name: Publish Packages
        run: |
          yarn global add lerna
          CHANGED_PACKAGES=$(lerna ls --since HEAD~1 --json)
          for package in $CHANGED_PACKAGES; do
            cd $package
            lerna exec --concurrency 1 -- yarn publish --access public
            cd ..
          done

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}